AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  SkillAppUserSkillManager:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::748492294422:role/SkillApp-LambdaRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/{user_id}/{skill}'
            Method: PUT
        Api2:
          Type: Api
          Properties:
            Path: '/{user_id}/{skill}'
            Method: GET
      Environment:
        Variables:
          AUTH_GROUP: SkillApp-Cognito-Admin-Group
          PROFILE_TABLE: SkillApp-User-Profiles
