AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  SkillAppSchemaManager:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::748492294422:role/SkillApp-LambdaRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: '/{record_name}'
            Method: PUT
        Api3:
          Type: Api
          Properties:
            Path: '/{record_name}'
            Method: DELETE
        Api4:
          Type: Api
          Properties:
            Path: '/{record_name}'
            Method: GET
        Api5:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Environment:
        Variables:
          AUTH_GROUP: SkillApp-Cognito-Admin-Group
